// Generated by gencpp from file tug_neo_locate_station/LocateStation.msg
// DO NOT EDIT!


#ifndef TUG_NEO_LOCATE_STATION_MESSAGE_LOCATESTATION_H
#define TUG_NEO_LOCATE_STATION_MESSAGE_LOCATESTATION_H

#include <ros/service_traits.h>


#include <tug_neo_locate_station/LocateStationRequest.h>
#include <tug_neo_locate_station/LocateStationResponse.h>


namespace tug_neo_locate_station
{

struct LocateStation
{

typedef LocateStationRequest Request;
typedef LocateStationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocateStation
} // namespace tug_neo_locate_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_neo_locate_station::LocateStation > {
  static const char* value()
  {
    return "80204a6ff2622a7071680d5597cbd3aa";
  }

  static const char* value(const ::tug_neo_locate_station::LocateStation&) { return value(); }
};

template<>
struct DataType< ::tug_neo_locate_station::LocateStation > {
  static const char* value()
  {
    return "tug_neo_locate_station/LocateStation";
  }

  static const char* value(const ::tug_neo_locate_station::LocateStation&) { return value(); }
};


// service_traits::MD5Sum< ::tug_neo_locate_station::LocateStationRequest> should match
// service_traits::MD5Sum< ::tug_neo_locate_station::LocateStation >
template<>
struct MD5Sum< ::tug_neo_locate_station::LocateStationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_neo_locate_station::LocateStation >::value();
  }
  static const char* value(const ::tug_neo_locate_station::LocateStationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_neo_locate_station::LocateStationRequest> should match
// service_traits::DataType< ::tug_neo_locate_station::LocateStation >
template<>
struct DataType< ::tug_neo_locate_station::LocateStationRequest>
{
  static const char* value()
  {
    return DataType< ::tug_neo_locate_station::LocateStation >::value();
  }
  static const char* value(const ::tug_neo_locate_station::LocateStationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_neo_locate_station::LocateStationResponse> should match
// service_traits::MD5Sum< ::tug_neo_locate_station::LocateStation >
template<>
struct MD5Sum< ::tug_neo_locate_station::LocateStationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_neo_locate_station::LocateStation >::value();
  }
  static const char* value(const ::tug_neo_locate_station::LocateStationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_neo_locate_station::LocateStationResponse> should match
// service_traits::DataType< ::tug_neo_locate_station::LocateStation >
template<>
struct DataType< ::tug_neo_locate_station::LocateStationResponse>
{
  static const char* value()
  {
    return DataType< ::tug_neo_locate_station::LocateStation >::value();
  }
  static const char* value(const ::tug_neo_locate_station::LocateStationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_NEO_LOCATE_STATION_MESSAGE_LOCATESTATION_H
