// Generated by gencpp from file tug_navigation_tools/calculate_rotationResponse.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_CALCULATE_ROTATIONRESPONSE_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_CALCULATE_ROTATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_navigation_tools
{
template <class ContainerAllocator>
struct calculate_rotationResponse_
{
  typedef calculate_rotationResponse_<ContainerAllocator> Type;

  calculate_rotationResponse_()
    : angle(0.0)  {
    }
  calculate_rotationResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calculate_rotationResponse_

typedef ::tug_navigation_tools::calculate_rotationResponse_<std::allocator<void> > calculate_rotationResponse;

typedef boost::shared_ptr< ::tug_navigation_tools::calculate_rotationResponse > calculate_rotationResponsePtr;
typedef boost::shared_ptr< ::tug_navigation_tools::calculate_rotationResponse const> calculate_rotationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tug_navigation_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_navigation_tools/calculate_rotationResponse";
  }

  static const char* value(const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
;
  }

  static const char* value(const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calculate_rotationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_navigation_tools::calculate_rotationResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_CALCULATE_ROTATIONRESPONSE_H
