// Generated by gencpp from file tug_navigation_tools/EmergencyStop.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_EMERGENCYSTOP_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_EMERGENCYSTOP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_navigation_tools
{
template <class ContainerAllocator>
struct EmergencyStop_
{
  typedef EmergencyStop_<ContainerAllocator> Type;

  EmergencyStop_()
    : stop_cmd(false)  {
    }
  EmergencyStop_(const ContainerAllocator& _alloc)
    : stop_cmd(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_cmd_type;
  _stop_cmd_type stop_cmd;





  typedef boost::shared_ptr< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> const> ConstPtr;

}; // struct EmergencyStop_

typedef ::tug_navigation_tools::EmergencyStop_<std::allocator<void> > EmergencyStop;

typedef boost::shared_ptr< ::tug_navigation_tools::EmergencyStop > EmergencyStopPtr;
typedef boost::shared_ptr< ::tug_navigation_tools::EmergencyStop const> EmergencyStopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator2> & rhs)
{
  return lhs.stop_cmd == rhs.stop_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tug_navigation_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8c75689c02fa4ef8f26e5152b43ecdd";
  }

  static const char* value(const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8c75689c02fa4efULL;
  static const uint64_t static_value2 = 0x8f26e5152b43ecddULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_navigation_tools/EmergencyStop";
  }

  static const char* value(const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stop_cmd\n"
;
  }

  static const char* value(const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmergencyStop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_navigation_tools::EmergencyStop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_navigation_tools::EmergencyStop_<ContainerAllocator>& v)
  {
    s << indent << "stop_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_EMERGENCYSTOP_H
