// Generated by gencpp from file tug_navigation_tools/FinePositioning.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_FINEPOSITIONING_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_FINEPOSITIONING_H

#include <ros/service_traits.h>


#include <tug_navigation_tools/FinePositioningRequest.h>
#include <tug_navigation_tools/FinePositioningResponse.h>


namespace tug_navigation_tools
{

struct FinePositioning
{

typedef FinePositioningRequest Request;
typedef FinePositioningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FinePositioning
} // namespace tug_navigation_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_navigation_tools::FinePositioning > {
  static const char* value()
  {
    return "171c107e3dd8cdfa8ae691b15d06b1d1";
  }

  static const char* value(const ::tug_navigation_tools::FinePositioning&) { return value(); }
};

template<>
struct DataType< ::tug_navigation_tools::FinePositioning > {
  static const char* value()
  {
    return "tug_navigation_tools/FinePositioning";
  }

  static const char* value(const ::tug_navigation_tools::FinePositioning&) { return value(); }
};


// service_traits::MD5Sum< ::tug_navigation_tools::FinePositioningRequest> should match
// service_traits::MD5Sum< ::tug_navigation_tools::FinePositioning >
template<>
struct MD5Sum< ::tug_navigation_tools::FinePositioningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::FinePositioning >::value();
  }
  static const char* value(const ::tug_navigation_tools::FinePositioningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::FinePositioningRequest> should match
// service_traits::DataType< ::tug_navigation_tools::FinePositioning >
template<>
struct DataType< ::tug_navigation_tools::FinePositioningRequest>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::FinePositioning >::value();
  }
  static const char* value(const ::tug_navigation_tools::FinePositioningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_navigation_tools::FinePositioningResponse> should match
// service_traits::MD5Sum< ::tug_navigation_tools::FinePositioning >
template<>
struct MD5Sum< ::tug_navigation_tools::FinePositioningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::FinePositioning >::value();
  }
  static const char* value(const ::tug_navigation_tools::FinePositioningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::FinePositioningResponse> should match
// service_traits::DataType< ::tug_navigation_tools::FinePositioning >
template<>
struct DataType< ::tug_navigation_tools::FinePositioningResponse>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::FinePositioning >::value();
  }
  static const char* value(const ::tug_navigation_tools::FinePositioningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_FINEPOSITIONING_H
