// Generated by gencpp from file tug_navigation_tools/parking_positionRequest.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_PARKING_POSITIONREQUEST_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_PARKING_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_navigation_tools
{
template <class ContainerAllocator>
struct parking_positionRequest_
{
  typedef parking_positionRequest_<ContainerAllocator> Type;

  parking_positionRequest_()
    : x(0.0)
    , y(0.0)
    , distance(0.0)  {
    }
  parking_positionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct parking_positionRequest_

typedef ::tug_navigation_tools::parking_positionRequest_<std::allocator<void> > parking_positionRequest;

typedef boost::shared_ptr< ::tug_navigation_tools::parking_positionRequest > parking_positionRequestPtr;
typedef boost::shared_ptr< ::tug_navigation_tools::parking_positionRequest const> parking_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tug_navigation_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68b34e16807f733f1339ca745bc48a1b";
  }

  static const char* value(const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68b34e16807f733fULL;
  static const uint64_t static_value2 = 0x1339ca745bc48a1bULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_navigation_tools/parking_positionRequest";
  }

  static const char* value(const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# x-position of the table\n"
"float64 x\n"
"\n"
"# y-position of the table\n"
"float64 y\n"
"\n"
"# distance between border of table and Eisenschwein\n"
"float64 distance\n"
"\n"
;
  }

  static const char* value(const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct parking_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_navigation_tools::parking_positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_PARKING_POSITIONREQUEST_H
