// Generated by gencpp from file tug_navigation_tools/PrenavigationPathplannerRequest.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNERREQUEST_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_navigation_tools
{
template <class ContainerAllocator>
struct PrenavigationPathplannerRequest_
{
  typedef PrenavigationPathplannerRequest_<ContainerAllocator> Type;

  PrenavigationPathplannerRequest_()
    {
    }
  PrenavigationPathplannerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PrenavigationPathplannerRequest_

typedef ::tug_navigation_tools::PrenavigationPathplannerRequest_<std::allocator<void> > PrenavigationPathplannerRequest;

typedef boost::shared_ptr< ::tug_navigation_tools::PrenavigationPathplannerRequest > PrenavigationPathplannerRequestPtr;
typedef boost::shared_ptr< ::tug_navigation_tools::PrenavigationPathplannerRequest const> PrenavigationPathplannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tug_navigation_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_navigation_tools/PrenavigationPathplannerRequest";
  }

  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#nav_msgs/Path path\n"
;
  }

  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrenavigationPathplannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tug_navigation_tools::PrenavigationPathplannerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNERREQUEST_H
