// Generated by gencpp from file tug_navigation_tools/PrenavigationPathplanner.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNER_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNER_H

#include <ros/service_traits.h>


#include <tug_navigation_tools/PrenavigationPathplannerRequest.h>
#include <tug_navigation_tools/PrenavigationPathplannerResponse.h>


namespace tug_navigation_tools
{

struct PrenavigationPathplanner
{

typedef PrenavigationPathplannerRequest Request;
typedef PrenavigationPathplannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PrenavigationPathplanner
} // namespace tug_navigation_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_navigation_tools::PrenavigationPathplanner > {
  static const char* value()
  {
    return "80204a6ff2622a7071680d5597cbd3aa";
  }

  static const char* value(const ::tug_navigation_tools::PrenavigationPathplanner&) { return value(); }
};

template<>
struct DataType< ::tug_navigation_tools::PrenavigationPathplanner > {
  static const char* value()
  {
    return "tug_navigation_tools/PrenavigationPathplanner";
  }

  static const char* value(const ::tug_navigation_tools::PrenavigationPathplanner&) { return value(); }
};


// service_traits::MD5Sum< ::tug_navigation_tools::PrenavigationPathplannerRequest> should match
// service_traits::MD5Sum< ::tug_navigation_tools::PrenavigationPathplanner >
template<>
struct MD5Sum< ::tug_navigation_tools::PrenavigationPathplannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::PrenavigationPathplanner >::value();
  }
  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::PrenavigationPathplannerRequest> should match
// service_traits::DataType< ::tug_navigation_tools::PrenavigationPathplanner >
template<>
struct DataType< ::tug_navigation_tools::PrenavigationPathplannerRequest>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::PrenavigationPathplanner >::value();
  }
  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_navigation_tools::PrenavigationPathplannerResponse> should match
// service_traits::MD5Sum< ::tug_navigation_tools::PrenavigationPathplanner >
template<>
struct MD5Sum< ::tug_navigation_tools::PrenavigationPathplannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::PrenavigationPathplanner >::value();
  }
  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::PrenavigationPathplannerResponse> should match
// service_traits::DataType< ::tug_navigation_tools::PrenavigationPathplanner >
template<>
struct DataType< ::tug_navigation_tools::PrenavigationPathplannerResponse>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::PrenavigationPathplanner >::value();
  }
  static const char* value(const ::tug_navigation_tools::PrenavigationPathplannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_PRENAVIGATIONPATHPLANNER_H
