// Generated by gencpp from file tug_navigation_tools/rotational_movement.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_ROTATIONAL_MOVEMENT_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_ROTATIONAL_MOVEMENT_H

#include <ros/service_traits.h>


#include <tug_navigation_tools/rotational_movementRequest.h>
#include <tug_navigation_tools/rotational_movementResponse.h>


namespace tug_navigation_tools
{

struct rotational_movement
{

typedef rotational_movementRequest Request;
typedef rotational_movementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rotational_movement
} // namespace tug_navigation_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_navigation_tools::rotational_movement > {
  static const char* value()
  {
    return "b8e92220d3a386937ac91ac3abd87983";
  }

  static const char* value(const ::tug_navigation_tools::rotational_movement&) { return value(); }
};

template<>
struct DataType< ::tug_navigation_tools::rotational_movement > {
  static const char* value()
  {
    return "tug_navigation_tools/rotational_movement";
  }

  static const char* value(const ::tug_navigation_tools::rotational_movement&) { return value(); }
};


// service_traits::MD5Sum< ::tug_navigation_tools::rotational_movementRequest> should match
// service_traits::MD5Sum< ::tug_navigation_tools::rotational_movement >
template<>
struct MD5Sum< ::tug_navigation_tools::rotational_movementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::rotational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::rotational_movementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::rotational_movementRequest> should match
// service_traits::DataType< ::tug_navigation_tools::rotational_movement >
template<>
struct DataType< ::tug_navigation_tools::rotational_movementRequest>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::rotational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::rotational_movementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_navigation_tools::rotational_movementResponse> should match
// service_traits::MD5Sum< ::tug_navigation_tools::rotational_movement >
template<>
struct MD5Sum< ::tug_navigation_tools::rotational_movementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::rotational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::rotational_movementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::rotational_movementResponse> should match
// service_traits::DataType< ::tug_navigation_tools::rotational_movement >
template<>
struct DataType< ::tug_navigation_tools::rotational_movementResponse>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::rotational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::rotational_movementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_ROTATIONAL_MOVEMENT_H
