// Generated by gencpp from file tug_navigation_tools/rotate_to_angleRequest.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_ROTATE_TO_ANGLEREQUEST_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_ROTATE_TO_ANGLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_navigation_tools
{
template <class ContainerAllocator>
struct rotate_to_angleRequest_
{
  typedef rotate_to_angleRequest_<ContainerAllocator> Type;

  rotate_to_angleRequest_()
    : desired_phi(0.0)  {
    }
  rotate_to_angleRequest_(const ContainerAllocator& _alloc)
    : desired_phi(0.0)  {
  (void)_alloc;
    }



   typedef double _desired_phi_type;
  _desired_phi_type desired_phi;





  typedef boost::shared_ptr< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rotate_to_angleRequest_

typedef ::tug_navigation_tools::rotate_to_angleRequest_<std::allocator<void> > rotate_to_angleRequest;

typedef boost::shared_ptr< ::tug_navigation_tools::rotate_to_angleRequest > rotate_to_angleRequestPtr;
typedef boost::shared_ptr< ::tug_navigation_tools::rotate_to_angleRequest const> rotate_to_angleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.desired_phi == rhs.desired_phi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator1> & lhs, const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tug_navigation_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0dbfda91b67897009c61f944e40620f";
  }

  static const char* value(const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0dbfda91b678970ULL;
  static const uint64_t static_value2 = 0x09c61f944e40620fULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_navigation_tools/rotate_to_angleRequest";
  }

  static const char* value(const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 desired_phi\n"
;
  }

  static const char* value(const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired_phi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rotate_to_angleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_navigation_tools::rotate_to_angleRequest_<ContainerAllocator>& v)
  {
    s << indent << "desired_phi: ";
    Printer<double>::stream(s, indent + "  ", v.desired_phi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_ROTATE_TO_ANGLEREQUEST_H
