// Generated by gencpp from file tug_navigation_tools/translational_movement.msg
// DO NOT EDIT!


#ifndef TUG_NAVIGATION_TOOLS_MESSAGE_TRANSLATIONAL_MOVEMENT_H
#define TUG_NAVIGATION_TOOLS_MESSAGE_TRANSLATIONAL_MOVEMENT_H

#include <ros/service_traits.h>


#include <tug_navigation_tools/translational_movementRequest.h>
#include <tug_navigation_tools/translational_movementResponse.h>


namespace tug_navigation_tools
{

struct translational_movement
{

typedef translational_movementRequest Request;
typedef translational_movementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct translational_movement
} // namespace tug_navigation_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_navigation_tools::translational_movement > {
  static const char* value()
  {
    return "0394d208a08b3715c1bf38023b0d4e4e";
  }

  static const char* value(const ::tug_navigation_tools::translational_movement&) { return value(); }
};

template<>
struct DataType< ::tug_navigation_tools::translational_movement > {
  static const char* value()
  {
    return "tug_navigation_tools/translational_movement";
  }

  static const char* value(const ::tug_navigation_tools::translational_movement&) { return value(); }
};


// service_traits::MD5Sum< ::tug_navigation_tools::translational_movementRequest> should match
// service_traits::MD5Sum< ::tug_navigation_tools::translational_movement >
template<>
struct MD5Sum< ::tug_navigation_tools::translational_movementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::translational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::translational_movementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::translational_movementRequest> should match
// service_traits::DataType< ::tug_navigation_tools::translational_movement >
template<>
struct DataType< ::tug_navigation_tools::translational_movementRequest>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::translational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::translational_movementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_navigation_tools::translational_movementResponse> should match
// service_traits::MD5Sum< ::tug_navigation_tools::translational_movement >
template<>
struct MD5Sum< ::tug_navigation_tools::translational_movementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_navigation_tools::translational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::translational_movementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_navigation_tools::translational_movementResponse> should match
// service_traits::DataType< ::tug_navigation_tools::translational_movement >
template<>
struct DataType< ::tug_navigation_tools::translational_movementResponse>
{
  static const char* value()
  {
    return DataType< ::tug_navigation_tools::translational_movement >::value();
  }
  static const char* value(const ::tug_navigation_tools::translational_movementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_NAVIGATION_TOOLS_MESSAGE_TRANSLATIONAL_MOVEMENT_H
